"""Your migration message

Revision ID: 360d65fdad7e
Revises: 0fd5c41c128d
Create Date: 2025-01-11 07:24:33.131856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360d65fdad7e'
down_revision = '0fd5c41c128d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.VARCHAR(length=16), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
