"""Your migration message here

Revision ID: 4411d3bc6883
Revises: 360d65fdad7e
Create Date: 2025-01-11 11:32:09.658244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4411d3bc6883'
down_revision = '360d65fdad7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_oauth_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_oauth_user')

    # ### end Alembic commands ###
