"""Your migration message here

Revision ID: a3c8a9a76a28
Revises: 4411d3bc6883
Create Date: 2025-01-11 11:46:27.614160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c8a9a76a28'
down_revision = '4411d3bc6883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_oauth_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_oauth_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
